"use client"

import { create } from "zustand"

export interface Product {
  id: number
  name: string
  price: number
  image: string
  category: string
  gender: string
  color: string
  size: string[]
  brand: string
  material: string
  rating: number
  isNew: boolean
  isFavorite: boolean
}

export interface CartItem extends Product {
  quantity: number
  selectedSize: string
}

interface Store {
  favorites: Product[]
  cartItems: CartItem[]
  toggleFavorite: (productId: number) => void
  updateCartQuantity: (productId: number, change: number) => void
  removeFromCart: (productId: number) => void
  addToCart: (product: Product, selectedSize?: string) => void
}

const products: Product[] = [
  // T-shirts - Men
  {
    id: 1,
    name: "Classic Cotton T-Shirt",
    price: 25,
    image: "https://perfectwhitetee.com/cdn/shop/files/RUBY_WHITE_02856_400x.jpg?v=1715036122",
    category: "T-shirts",
    gender: "Women",
    color: "White",
    size: ["S", "M", "L", "XL"],
    brand: "H&M",
    material: "Cotton",
    rating: 4.5,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 2,
    name: "Premium Basic Tee",
    price: 35,
    image: "https://m-commerce.witchery.co.nz/productimages_display/MAGNIFY/1/28753_186744_205817.jpg",
    category: "T-shirts",
    gender: "Women",
    color: "Black",
    size: ["M", "L", "XL", "XXL"],
    brand: "Zara",
    material: "Cotton",
    rating: 4.7,
    isNew: true,
    isFavorite: false,
  },
  {
    id: 3,
    name: "Vintage Style T-Shirt",
    price: 30,
    image: "https://perfectlypaisleyshop.com/cdn/shop/files/18821643_63a01d69-a581-43ac-b4ba-b6e6ef8b88b4_grande.jpg?v=1699977409",
    category: "T-shirts",
    gender: "Women",
    color: "Gray",
    size: ["S", "M", "L"],
    brand: "Mango",
    material: "Cotton",
    rating: 4.3,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 4,
    name: "Graphic Print Tee",
    price: 28,
    image: "https://m.media-amazon.com/images/I/71QMsrys-lL._UY1000_.jpg",
    category: "T-shirts",
    gender: "Women",
    color: "Blue",
    size: ["M", "L", "XL"],
    brand: "Pull&Bear",
    material: "Cotton",
    rating: 4.2,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 5,
    name: "Organic Cotton T-Shirt",
    price: 40,
    image: "https://theclassictshirt.com/cdn/shop/files/main_mckenna_cre_elbow_aligned_1.png?v=1741718042&width=1500",
    category: "T-shirts",
    gender: "Women",
    color: "Green",
    size: ["S", "M", "L", "XL"],
    brand: "H&M",
    material: "Cotton",
    rating: 4.6,
    isNew: true,
    isFavorite: false,
  },

  // T-shirts - Women
  {
    id: 6,
    name: "Soft Cotton Tee",
    price: 22,
    image: "https://i.etsystatic.com/44657115/r/il/84d5ab/5753966541/il_570xN.5753966541_bb2y.jpg",
    category: "T-shirts",
    gender: "Women",
    color: "Pink",
    size: ["XS", "S", "M", "L"],
    brand: "Zara",
    material: "Cotton",
    rating: 4.4,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 7,
    name: "Fitted Basic T-Shirt",
    price: 26,
    image: "https://cdn-img.prettylittlething.com/d/4/e/2/d4e2a62c314140d950a380dfdcf0ebc1e44fbb4a_CMP1946_1_basic_white_cotton_blend_fitted_crew_neck_t_shirt.jpg",
    category: "T-shirts",
    gender: "Women",
    color: "White",
    size: ["XS", "S", "M"],
    brand: "Bershka",
    material: "Cotton",
    rating: 4.3,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 8,
    name: "Oversized Tee",
    price: 32,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLKmFJnUgJ-Ea-nKL0oI44dwnjLlcLhlT8Hw&s",
    category: "T-shirts",
    gender: "Women",
    color: "Beige",
    size: ["S", "M", "L", "XL"],
    brand: "Stradivarius",
    material: "Cotton",
    rating: 4.5,
    isNew: true,
    isFavorite: false,
  },
  {
    id: 9,
    name: "V-Neck T-Shirt",
    price: 24,
    image: "https://duer.ca/cdn/shop/products/WTJR820-ONLY-TEE-V-NECK-BLACK_0433_2.jpg?v=1744671478&width=1080",
    category: "T-shirts",
    gender: "Women",
    color: "Black",
    size: ["XS", "S", "M", "L"],
    brand: "Mango",
    material: "Cotton",
    rating: 4.2,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 10,
    name: "Striped Cotton Tee",
    price: 29,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSnahLHEs24z9c9TOuiV_xmCUN15fgAB5u4g&s",
    category: "T-shirts",
    gender: "Women",
    color: "Blue",
    size: ["S", "M", "L"],
    brand: "H&M",
    material: "Cotton",
    rating: 4.4,
    isNew: false,
    isFavorite: false,
  },

  // Shirts - Men
  {
    id: 11,
    name: "Formal White Shirt",
    price: 65,
    image: "https://savilerowco.com/cdn/shop/files/white-poplin-classic-fit-shirt-011wht_model-image.jpg?v=1722024923&width=800",
    category: "Shirts",
    gender: "Men",
    color: "White",
    size: ["M", "L", "XL", "XXL"],
    brand: "Zara",
    material: "Cotton",
    rating: 4.6,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 12,
    name: "Casual Denim Shirt",
    price: 55,
    image: "https://uathayam.in/cdn/shop/files/250420_uathayam_ecom24096_244a4ee5-92ca-4ae1-86b3-04987f70ee1d_1800x1800.jpg?v=1741863030",
    category: "Shirts",
    gender: "Men",
    color: "Blue",
    size: ["S", "M", "L", "XL"],
    brand: "H&M",
    material: "Denim",
    rating: 4.3,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 13,
    name: "Linen Summer Shirt",
    price: 70,
    image: "https://magiclinen.com/cdn/shop/products/mens-linen-shirt-nevada-in-matcha-green-1.jpg?crop=center&height=500&v=1661172505&width=400",
    category: "Shirts",
    gender: "Men",
    color: "Beige",
    size: ["M", "L", "XL"],
    brand: "Mango",
    material: "Linen",
    rating: 4.5,
    isNew: true,
    isFavorite: false,
  },
  {
    id: 14,
    name: "Checkered Flannel Shirt",
    price: 48,
    image: "https://buffalojackson.com/cdn/shop/products/classic-mens-fairbanks-flannel-red-plaid-2_800x.jpg?v=1662061252",
    category: "Shirts",
    gender: "Men",
    color: "Red",
    size: ["S", "M", "L", "XL"],
    brand: "Pull&Bear",
    material: "Cotton",
    rating: 4.2,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 15,
    name: "Oxford Button-Down",
    price: 75,
    image: "https://content.moss.co.uk/images/extraextralarge/966920701_01.jpg",
    category: "Shirts",
    gender: "Men",
    color: "Gray",
    size: ["M", "L", "XL", "XXL"],
    brand: "Zara",
    material: "Cotton",
    rating: 4.7,
    isNew: false,
    isFavorite: false,
  },

  // Shirts - Women
  {
    id: 16,
    name: "Silk Blouse",
    price: 85,
    image: "https://i.etsystatic.com/18413879/r/il/e4adcc/4611216097/il_300x300.4611216097_dz0b.jpg",
    category: "Shirts",
    gender: "Women",
    color: "White",
    size: ["XS", "S", "M", "L"],
    brand: "Zara",
    material: "Silk",
    rating: 4.8,
    isNew: true,
    isFavorite: false,
  },
  {
    id: 17,
    name: "Cotton Work Shirt",
    price: 52,
    image: "https://store.goldersaustralia.com.au/cdn/shop/files/MaryG-AusCotton-Womens-Shirt-Raspberry-Hero_55edb36c-5a5a-453c-8685-f3bca08d6477.jpg?v=1708494873",
    category: "Shirts",
    gender: "Women",
    color: "Blue",
    size: ["S", "M", "L"],
    brand: "Mango",
    material: "Cotton",
    rating: 4.4,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 18,
    name: "Floral Print Blouse",
    price: 58,
    image: "https://www.baukjen.com/cdn/shop/files/328_SH40295-BVO_TR40373-BLK_3_55d244f1-58dc-49f9-b2e3-ba6164157722.jpg?v=1738336119&width=1946",
    category: "Shirts",
    gender: "Women",
    color: "Pink",
    size: ["XS", "S", "M", "L"],
    brand: "H&M",
    material: "Viscose",
    rating: 4.3,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 19,
    name: "Oversized Shirt",
    price: 62,
    image: "https://media.boohoo.com/i/boohoo/gzz57720_pale%20grey_xl/female-pale%20grey-linen-look-striped-oversized-shirt-&-shorts/?w=900&qlt=default&fmt.jp2.qlt=70&fmt=auto&sm=fit",
    category: "Shirts",
    gender: "Women",
    color: "Black",
    size: ["S", "M", "L", "XL"],
    brand: "Bershka",
    material: "Cotton",
    rating: 4.5,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 20,
    name: "Satin Dress Shirt",
    price: 78,
    image: "https://shop.mango.com/assets/rcs/pics/static/T5/fotos/S/57003777_44.jpg?imwidth=2048&imdensity=1&ts=1694100779268",
    category: "Shirts",
    gender: "Women",
    color: "Beige",
    size: ["XS", "S", "M"],
    brand: "Stradivarius",
    material: "Satin",
    rating: 4.6,
    isNew: true,
    isFavorite: false,
  },

  // Dresses - Women
  {
    id: 21,
    name: "Summer Maxi Dress",
    price: 95,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZBbW-wwx1pJlBBTDODErvIJynGLH1mqlmIw&s",
    category: "Dresses",
    gender: "Women",
    color: "Blue",
    size: ["XS", "S", "M", "L"],
    brand: "Zara",
    material: "Viscose",
    rating: 4.7,
    isNew: true,
    isFavorite: false,
  },
  {
    id: 22,
    name: "Little Black Dress",
    price: 120,
    image: "https://shegoeswear.com/cdn/shop/files/Untitleddesign_7_copy.png?v=1711642823",
    category: "Dresses",
    gender: "Women",
    color: "Black",
    size: ["XS", "S", "M", "L"],
    brand: "Mango",
    material: "Polyester",
    rating: 4.8,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 23,
    name: "Floral Midi Dress",
    price: 85,
    image: "https://www.reddress.com/cdn/shop/files/013_DSCF8633_Copyright_LoganPotterf_2024.jpg?v=1717422850",
    category: "Dresses",
    gender: "Women",
    color: "Pink",
    size: ["S", "M", "L"],
    brand: "H&M",
    material: "Cotton",
    rating: 4.5,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 24,
    name: "Casual Shirt Dress",
    price: 68,
    image: "https://m.media-amazon.com/images/I/81IjcvV9jzL._UY1000_.jpg",
    category: "Dresses",
    gender: "Women",
    color: "White",
    size: ["XS", "S", "M", "L", "XL"],
    brand: "Bershka",
    material: "Cotton",
    rating: 4.3,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 25,
    name: "Evening Cocktail Dress",
    price: 150,
    image: "https://ae01.alicdn.com/kf/S07d38c09001e43dfb24fac4bbd9c327cB.jpg",
    category: "Dresses",
    gender: "Women",
    color: "Red",
    size: ["XS", "S", "M"],
    brand: "Zara",
    material: "Satin",
    rating: 4.9,
    isNew: true,
    isFavorite: false,
  },

  // Dresses - Kids
  {
    id: 26,
    name: "Kids Summer Dress",
    price: 35,
    image: "https://cdn.shopify.com/s/files/1/0346/5021/products/lace-morning-gown-strasburg-children-girl-white-beach-dress-portrait-summer-vacation-ivory-lace-flower-girl-dresses-28265260417106.jpg?v=1749559673",
    category: "Dresses",
    gender: "Kids",
    color: "Pink",
    size: ["XS", "S", "M"],
    brand: "H&M",
    material: "Cotton",
    rating: 4.4,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 27,
    name: "Party Dress for Girls",
    price: 45,
    image: "https://lagorii.com/cdn/shop/files/black-princess-party-gown-a-royal-look-for-girls-lagorii-kids-1.jpg?v=1703715113",
    category: "Dresses",
    gender: "Kids",
    color: "Blue",
    size: ["XS", "S"],
    brand: "Zara",
    material: "Polyester",
    rating: 4.6,
    isNew: true,
    isFavorite: false,
  },
  {
    id: 28,
    name: "Casual Kids Dress",
    price: 28,
    image: "https://lagorii.com/cdn/shop/files/black-princess-party-gown-a-royal-look-for-girls-lagorii-kids-1.jpg?v=1703715113",
    category: "Dresses",
    gender: "Kids",
    color: "White",
    size: ["XS", "S", "M"],
    brand: "Mango",
    material: "Cotton",
    rating: 4.2,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 29,
    name: "Floral Kids Dress",
    price: 32,
    image: "https://www.handrlondon.com/product_image/1673454363566%20K%20FRONT.jpg",
    category: "Dresses",
    gender: "Kids",
    color: "Green",
    size: ["XS", "S"],
    brand: "H&M",
    material: "Cotton",
    rating: 4.3,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 30,
    name: "Princess Style Dress",
    price: 55,
    image: "https://m.media-amazon.com/images/I/71C-JUawWRS._UF894,1000_QL80_.jpg",
    category: "Dresses",
    gender: "Kids",
    color: "Pink",
    size: ["XS", "S", "M"],
    brand: "Zara",
    material: "Satin",
    rating: 4.7,
    isNew: true,
    isFavorite: false,
  },

  // Jeans - Men
  {
    id: 31,
    name: "Classic Straight Jeans",
    price: 75,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTd4eUAQ8Zu2VjR8ljp94yi43jx6e2bhpo9oQ&s",
    category: "Jeans",
    gender: "Men",
    color: "Blue",
    size: ["M", "L", "XL", "XXL"],
    brand: "Zara",
    material: "Denim",
    rating: 4.5,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 32,
    name: "Slim Fit Jeans",
    price: 68,
    image: "https://luxuryoutletonline.eu/25641-large_default_new/gianni-kavanagh-light-blue-slim-fit-jeans.jpg",
    category: "Jeans",
    gender: "Men",
    color: "Black",
    size: ["S", "M", "L", "XL"],
    brand: "H&M",
    material: "Denim",
    rating: 4.4,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 33,
    name: "Relaxed Fit Jeans",
    price: 82,
    image: "https://assemblylabel.com/cdn/shop/files/Mens_Relaxed_Jean3_600x.jpg?v=1748597075",
    category: "Jeans",
    gender: "Men",
    color: "Blue",
    size: ["M", "L", "XL", "XXL"],
    brand: "Mango",
    material: "Denim",
    rating: 4.3,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 34,
    name: "Distressed Jeans",
    price: 95,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRS9G17nez341RCj2n081j97cX41WlHvyFT4A&s",
    category: "Jeans",
    gender: "Men",
    color: "Blue",
    size: ["S", "M", "L", "XL"],
    brand: "Pull&Bear",
    material: "Denim",
    rating: 4.2,
    isNew: true,
    isFavorite: false,
  },
  {
    id: 35,
    name: "Dark Wash Jeans",
    price: 88,
    image: "https://cdn.shopify.com/s/files/1/0108/7802/files/LA_leather_jacket_2_web.jpg?v=1549312233",
    category: "Jeans",
    gender: "Men",
    color: "Black",
    size: ["M", "L", "XL"],
    brand: "Zara",
    material: "Denim",
    rating: 4.6,
    isNew: false,
    isFavorite: false,
  },

  // Jeans - Women
  {
    id: 36,
    name: "High-Waisted Jeans",
    price: 72,
    image: "https://abrandjeans.com/_next/image?url=https%3A%2F%2Fcdn.shopify.com%2Fs%2Ffiles%2F1%2F0376%2F2762%2F5611%2Ffiles%2FPDP-94WIDEEVA.jpg%3Fv%3D1747620460&w=3840&q=80",
    category: "Jeans",
    gender: "Women",
    color: "Blue",
    size: ["XS", "S", "M", "L"],
    brand: "Zara",
    material: "Denim",
    rating: 4.7,
    isNew: true,
    isFavorite: false,
  },
  {
    id: 37,
    name: "Skinny Jeans",
    price: 65,
    image: "https://media2.newlookassets.com/i/newlook/836199541M1/womens/clothing/jeans/navy-lift-shape-high-waist-yazmin-skinny-jeans.jpg",
    category: "Jeans",
    gender: "Women",
    color: "Black",
    size: ["XS", "S", "M", "L"],
    brand: "H&M",
    material: "Denim",
    rating: 4.5,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 38,
    name: "Mom Jeans",
    price: 78,
    image: "https://cdn-img.prettylittlething.com/c/3/5/c/c35cbfafbf24ac6679fb5684f635a37b153ac66e_CNL6139_1_prettylittlething_light_blue_wash_high_waist_mom_jeans.jpg?imwidth=600",
    category: "Jeans",
    gender: "Women",
    color: "Blue",
    size: ["S", "M", "L", "XL"],
    brand: "Bershka",
    material: "Denim",
    rating: 4.4,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 39,
    name: "Bootcut Jeans",
    price: 70,
    image: "https://images.rockandrepublic.com/is/image/rockandrepublic/112325242-HERO?$PDP24-XXLARGE$&fit=crop",
    category: "Jeans",
    gender: "Women",
    color: "Blue",
    size: ["XS", "S", "M", "L"],
    brand: "Mango",
    material: "Denim",
    rating: 4.3,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 40,
    name: "Ripped Jeans",
    price: 85,
    image: "https://rippedjeans.co/wp-content/uploads/2021/06/R073-1.jpg",
    category: "Jeans",
    gender: "Women",
    color: "Blue",
    size: ["S", "M", "L"],
    brand: "Stradivarius",
    material: "Denim",
    rating: 4.2,
    isNew: true,
    isFavorite: false,
  },

  // Jackets - Men
  {
    id: 41,
    name: "Leather Jacket",
    price: 180,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ32r2q0-N5PhtG4H5U3cDbWFyx7ilkI3HaJQ&s",
    category: "Jackets",
    gender: "Men",
    color: "Black",
    size: ["M", "L", "XL"],
    brand: "Zara",
    material: "Leather",
    rating: 4.8,
    isNew: true,
    isFavorite: false,
  },
  {
    id: 42,
    name: "Denim Jacket",
    price: 85,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVBEUSGEDY5GANdS_OoFORtuHvkoS41I1axDk0MNSAdBB1bY5FhqPB7pZ3kW1RtTrZaKY&usqp=CAU",
    category: "Jackets",
    gender: "Men",
    color: "Blue",
    size: ["S", "M", "L", "XL"],
    brand: "H&M",
    material: "Denim",
    rating: 4.4,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 43,
    name: "Bomber Jacket",
    price: 95,
    image: "https://www.gorsuch.com/cdn/shop/files/M11_HERNO_CASH_BMBR_020-704-0172-navy-m.jpg?v=1721083229",
    category: "Jackets",
    gender: "Men",
    color: "Green",
    size: ["M", "L", "XL"],
    brand: "Pull&Bear",
    material: "Polyester",
    rating: 4.3,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 44,
    name: "Blazer Jacket",
    price: 125,
    image: "https://m.media-amazon.com/images/I/718BRQ6+Y+L._UY350_.jpg",
    category: "Jackets",
    gender: "Men",
    color: "Gray",
    size: ["M", "L", "XL", "XXL"],
    brand: "Mango",
    material: "Wool",
    rating: 4.6,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 45,
    name: "Windbreaker",
    price: 65,
    image: "https://m.media-amazon.com/images/I/81OxEoWSMUL._UY1000_.jpg",
    category: "Jackets",
    gender: "Men",
    color: "Blue",
    size: ["S", "M", "L", "XL"],
    brand: "Nike",
    material: "Polyester",
    rating: 4.2,
    isNew: false,
    isFavorite: false,
  },

  // Jackets - Women
  {
    id: 46,
    name: "Cropped Leather Jacket",
    price: 165,
    image: "https://cdn-img.prettylittlething.com/5/7/f/2/57f24c2d5e70f70faad7ba880ca7f524ee094b40_CMZ8088_2_black_oversized_belted_hem_cropped_biker_jacket.jpg",
    category: "Jackets",
    gender: "Women",
    color: "Black",
    size: ["XS", "S", "M", "L"],
    brand: "Zara",
    material: "Leather",
    rating: 4.7,
    isNew: true,
    isFavorite: false,
  },
  {
    id: 47,
    name: "Oversized Blazer",
    price: 98,
    image: "https://www.instyle.com/thmb/3kBfiqbIIjEGO65VgjrD6unGFiI=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Oversizedblazer-602d0608ad2941acb33351117d0b1821.jpg",
    category: "Jackets",
    gender: "Women",
    color: "Beige",
    size: ["S", "M", "L", "XL"],
    brand: "Mango",
    material: "Polyester",
    rating: 4.5,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 48,
    name: "Denim Jacket",
    price: 75,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRChip3G4XasTBstBNrdo9YBqrLjt1tjkWWXg&s",
    category: "Jackets",
    gender: "Women",
    color: "Blue",
    size: ["XS", "S", "M", "L"],
    brand: "H&M",
    material: "Denim",
    rating: 4.3,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 49,
    name: "Puffer Jacket",
    price: 110,
    image: "https://beyondyoga.com/cdn/shop/files/PC2244_ruby-red_0358.jpg?v=1745444212",
    category: "Jackets",
    gender: "Women",
    color: "Pink",
    size: ["S", "M", "L"],
    brand: "Bershka",
    material: "Polyester",
    rating: 4.4,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 50,
    name: "Trench Coat",
    price: 145,
    image: "https://freemans.scene7.com/is/image/OttoUK/600w/Sosandar-Camel-Belted-Longline-Trench-Coat-with-Hood~44C025FRSP.jpg",
    category: "Jackets",
    gender: "Women",
    color: "Beige",
    size: ["XS", "S", "M", "L"],
    brand: "Zara",
    material: "Cotton",
    rating: 4.8,
    isNew: true,
    isFavorite: false,
  },

  // Sportswear - Unisex
  {
    id: 51,
    name: "Running Shorts",
    price: 35,
    image: "https://assets.adidas.com/images/w_600,f_auto,q_auto/21ebf78313ac46a1a2bc4b5bdaed7f95_9366/Ultimate_HEAT.RDY_Shorts_Black_IT3449.jpg",
    category: "Sportswear",
    gender: "Unisex",
    color: "Black",
    size: ["S", "M", "L", "XL"],
    brand: "Nike",
    material: "Polyester",
    rating: 4.5,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 52,
    name: "Yoga Leggings",
    price: 45,
    image: "https://seayogi.myshopify.com/cdn/shop/products/Run-and-Relax-Shine-Yoga-Leggings-Beautiful-black-online-yoga-shop-lifestyle.jpg?v=1587585021",
    category: "Sportswear",
    gender: "Unisex",
    color: "Gray",
    size: ["XS", "S", "M", "L"],
    brand: "Adidas",
    material: "Polyester",
    rating: 4.6,
    isNew: true,
    isFavorite: false,
  },
  {
    id: 53,
    name: "Sports Bra",
    price: 28,
    image: "https://www.runningbare.com.au/productimages/magnify/1/2575_21583_10484.jpg",
    category: "Sportswear",
    gender: "Women",
    color: "Pink",
    size: ["XS", "S", "M", "L"],
    brand: "Nike",
    material: "Polyester",
    rating: 4.4,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 54,
    name: "Track Pants",
    price: 55,
    image: "https://5.imimg.com/data5/JM/PT/SF/SELLER-21185332/sports-wear-clothes-500x500.jpg",
    category: "Sportswear",
    gender: "Unisex",
    color: "Blue",
    size: ["S", "M", "L", "XL"],
    brand: "Adidas",
    material: "Polyester",
    rating: 4.3,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 55,
    name: "Athletic Tank Top",
    price: 32,
    image: "https://goalfive.com/cdn/shop/products/Advance-Tank-Black-Front_c46d7e51-5370-4cdb-9a6d-4890cbb4d6c5.jpg?v=1650152465",
    category: "Sportswear",
    gender: "Unisex",
    color: "White",
    size: ["S", "M", "L", "XL"],
    brand: "Puma",
    material: "Polyester",
    rating: 4.2,
    isNew: false,
    isFavorite: false,
  },

  // Hoodies - Unisex
  {
    id: 56,
    name: "Classic Hoodie",
    price: 65,
    image: "https://gettees.us/cdn/shop/files/PI-H-WCL-125-3.png?v=1746813799&width=2000",
    category: "Hoodies",
    gender: "Unisex",
    color: "Gray",
    size: ["S", "M", "L", "XL", "XXL"],
    brand: "H&M",
    material: "Cotton",
    rating: 4.5,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 57,
    name: "Oversized Hoodie",
    price: 75,
    image: "https://m.media-amazon.com/images/I/71nBrCkqTZL._UY350_.jpg",
    category: "Hoodies",
    gender: "Unisex",
    color: "Black",
    size: ["M", "L", "XL", "XXL"],
    brand: "Zara",
    material: "Cotton",
    rating: 4.6,
    isNew: true,
    isFavorite: false,
  },
  {
    id: 58,
    name: "Zip-Up Hoodie",
    price: 70,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjzMlowZqRgRiDP1-N9lOkq42mfrEen7tyyw&s",
    category: "Hoodies",
    gender: "Unisex",
    color: "Blue",
    size: ["S", "M", "L", "XL"],
    brand: "Nike",
    material: "Cotton",
    rating: 4.4,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 59,
    name: "Cropped Hoodie",
    price: 58,
    image: "https://thatssofetch.co.uk/cdn/shop/files/zaina_low_rise_sweatpants_grey_zaina_cropped_hoodie_grey_4_b0177c08-142a-4e32-9c7b-33907fce2f3f_680x.jpg?v=1730078647",
    category: "Hoodies",
    gender: "Women",
    color: "Pink",
    size: ["XS", "S", "M", "L"],
    brand: "Bershka",
    material: "Cotton",
    rating: 4.3,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 60,
    name: "Graphic Print Hoodie",
    price: 68,
    image: "https://img.kwcdn.com/product/Fancyalgo/VirtualModelMatting/3d8cddfa95b6df5c11f0a3305a4ca7e4.jpg?imageMogr2/auto-orient%7CimageView2/2/w/800/q/70/format/webp",
    category: "Hoodies",
    gender: "Unisex",
    color: "White",
    size: ["S", "M", "L", "XL"],
    brand: "Pull&Bear",
    material: "Cotton",
    rating: 4.2,
    isNew: false,
    isFavorite: false,
  },

  // Sweaters
  {
    id: 61,
    name: "Wool Sweater",
    price: 85,
    image: "https://cdn11.bigcommerce.com/s-s56em6w72d/images/stencil/1280x1280/products/2869/16859/C1347@Mlead__00972__76376__19190.1532844834.jpg?c=2",
    category: "Sweaters",
    gender: "Men",
    color: "Brown",
    size: ["M", "L", "XL"],
    brand: "Zara",
    material: "Wool",
    rating: 4.7,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 62,
    name: "Cashmere Pullover",
    price: 120,
    image: "https://puracashmere.com/cdn/shop/files/OversizedCashmerePullover-DarkOliveAlt1_2048x.jpg?v=1731009382",
    category: "Sweaters",
    gender: "Women",
    color: "Beige",
    size: ["XS", "S", "M", "L"],
    brand: "Mango",
    material: "Wool",
    rating: 4.8,
    isNew: true,
    isFavorite: false,
  },
  {
    id: 63,
    name: "Cable Knit Sweater",
    price: 75,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqsQKwJLz8uyHE1m-MYqe3cB84lhdJhbvFsA&s",
    category: "Sweaters",
    gender: "Unisex",
    color: "Gray",
    size: ["S", "M", "L", "XL"],
    brand: "H&M",
    material: "Knit",
    rating: 4.5,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 64,
    name: "Turtleneck Sweater",
    price: 68,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuXmxEskuAxzwDM8-W7n0c3x0sVgz-_4ibKg&s",
    category: "Sweaters",
    gender: "Women",
    color: "Black",
    size: ["XS", "S", "M", "L"],
    brand: "Zara",
    material: "Knit",
    rating: 4.4,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 65,
    name: "Cardigan",
    price: 78,
    image: "https://www.belladinotte.com/media/catalog/product/b/e/belladinotte_eloise_soft_blue_ladies_crew_cardigan_front_1.jpg?width=700&height=700&store=default&image-type=image",
    category: "Sweaters",
    gender: "Women",
    color: "Pink",
    size: ["S", "M", "L"],
    brand: "Stradivarius",
    material: "Knit",
    rating: 4.3,
    isNew: false,
    isFavorite: false,
  },

  // Shorts
  {
    id: 66,
    name: "Denim Shorts",
    price: 45,
    image: "https://whitefoxboutique.com/cdn/shop/files/IMG_1180_e6f24592-c0cf-4d2f-8906-7edc238a175d.jpg?v=1703027739",
    category: "Shorts",
    gender: "Women",
    color: "Blue",
    size: ["XS", "S", "M", "L"],
    brand: "H&M",
    material: "Denim",
    rating: 4.3,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 67,
    name: "Chino Shorts",
    price: 38,
    image: "https://mauvais.co.uk/cdn/shop/files/1_0ef6ec83-5f89-4b3e-9b69-9eca271667b4.jpg?v=1742989213&width=2668",
    category: "Shorts",
    gender: "Men",
    color: "Beige",
    size: ["S", "M", "L", "XL"],
    brand: "Zara",
    material: "Cotton",
    rating: 4.4,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 68,
    name: "High-Waisted Shorts",
    price: 42,
    image: "https://ae01.alicdn.com/kf/S14e5dbc87019473786159835738c101eP.jpg",
    category: "Shorts",
    gender: "Women",
    color: "Black",
    size: ["XS", "S", "M", "L"],
    brand: "Bershka",
    material: "Cotton",
    rating: 4.2,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 69,
    name: "Cargo Shorts",
    price: 52,
    image: "https://us.lskd.co/cdn/shop/products/energy-stretch-cargo-short-black-11_58da221e-4586-4d42-97cc-6151e13ecaba.jpg?v=1713832460&width=1080",
    category: "Shorts",
    gender: "Men",
    color: "Green",
    size: ["M", "L", "XL"],
    brand: "Pull&Bear",
    material: "Cotton",
    rating: 4.1,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 70,
    name: "Linen Shorts",
    price: 48,
    image: "https://magiclinen.com/cdn/shop/files/linen-shirt-CALPE-in-forest-green-gingham-CUENCA-shorts-0_f170dd87-e97b-42fd-8fbe-4c96f8ce42ba.jpg?v=1686556106&width=1946",
    category: "Shorts",
    gender: "Unisex",
    color: "White",
    size: ["S", "M", "L", "XL"],
    brand: "Mango",
    material: "Linen",
    rating: 4.5,
    isNew: true,
    isFavorite: false,
  },

  // Skirts
  {
    id: 71,
    name: "Mini Skirt",
    price: 35,
    image: "https://cdn.shopify.com/s/files/1/0293/9277/products/06-23-22Studio3_RM_RL_14-14-35_28_FN2070I400_LightBlueWash_P_0739_SG.jpg?v=1656100074",
    category: "Skirts",
    gender: "Women",
    color: "Black",
    size: ["XS", "S", "M", "L"],
    brand: "Zara",
    material: "Polyester",
    rating: 4.3,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 72,
    name: "Pleated Skirt",
    price: 48,
    image: "https://i5.walmartimages.com/seo/PIKADINGNIS-Vintage-Brown-Woolen-Mini-Skirt-Women-Korean-High-Waist-Pleated-Skirts-School-Girl-Uniform-Y2K-All-Match-Jk-Short-Skirt_d98a5da7-2ed5-464a-87f0-762db599626b.98252a8dad2f1fe050c1823a73170650.jpeg",
    category: "Skirts",
    gender: "Women",
    color: "Blue",
    size: ["XS", "S", "M"],
    brand: "H&M",
    material: "Polyester",
    rating: 4.4,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 73,
    name: "A-Line Skirt",
    price: 42,
    image: "https://www.back2linen.com/cdn/shop/products/wrap-skirt-long-linen-skirt-summer-skirt-a-line-skirt-laurel-dark_grey_b8e53424-fd1e-4c4a-aa0d-2f61daa21382.jpg?v=1698166348",
    category: "Skirts",
    gender: "Women",
    color: "Red",
    size: ["S", "M", "L"],
    brand: "Mango",
    material: "Cotton",
    rating: 4.2,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 74,
    name: "Pencil Skirt",
    price: 55,
    image: "https://katekasin.com/cdn/shop/files/02_-_1_acca3820-af3f-44f7-b511-ed31a86de8c1.jpg?v=1699003716",
    category: "Skirts",
    gender: "Women",
    color: "Gray",
    size: ["XS", "S", "M", "L"],
    brand: "Zara",
    material: "Polyester",
    rating: 4.5,
    isNew: true,
    isFavorite: false,
  },
  {
    id: 75,
    name: "Maxi Skirt",
    price: 65,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQc0MGlQcNOEdAOVW8IbKaw8JQz1jUIuGUlfQ&s",
    category: "Skirts",
    gender: "Women",
    color: "Green",
    size: ["S", "M", "L", "XL"],
    brand: "Stradivarius",
    material: "Viscose",
    rating: 4.6,
    isNew: false,
    isFavorite: false,
  },

  // Accessories
  {
    id: 76,
    name: "Leather Belt",
    price: 25,
    image: "https://teakwoodleathers.com/cdn/shop/products/T_BT_753_BR_1.jpg?v=1750933845",
    category: "Accessories",
    gender: "Unisex",
    color: "Brown",
    size: ["One Size"],
    brand: "Zara",
    material: "Leather",
    rating: 4.4,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 77,
    name: "Baseball Cap",
    price: 18,
    image: "https://store.moma.org/cdn/shop/files/2c429eea-2106-4bba-8927-26b872a44579_c6e407dd-2f4b-4e66-ba2e-161fac7e964a.jpg?v=1705509201",
    category: "Accessories",
    gender: "Unisex",
    color: "Black",
    size: ["One Size"],
    brand: "Nike",
    material: "Cotton",
    rating: 4.2,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 78,
    name: "Silk Scarf",
    price: 35,
    image: "https://store.newyorker.com/cdn/shop/files/TheSportingSceneBallCapinWhiteModel3.png?v=1701986355&width=1000",
    category: "Accessories",
    gender: "Women",
    color: "Pink",
    size: ["One Size"],
    brand: "H&M",
    material: "Silk",
    rating: 4.5,
    isNew: true,
    isFavorite: false,
  },
  {
    id: 79,
    name: "Sunglasses",
    price: 45,
    image: "https://static.zennioptical.com/production/products/general/T0/20/T02071619-model-image2.jpg?im=FaceCrop,algorithm=dnn",
    category: "Accessories",
    gender: "Unisex",
    color: "Black",
    size: ["One Size"],
    brand: "Zara",
    material: "Polyester",
    rating: 4.3,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 80,
    name: "Crossbody Bag",
    price: 65,
    image: "https://m.media-amazon.com/images/I/7180BzRSBZL._UY1000_.jpg",
    category: "Accessories",
    gender: "Women",
    color: "Beige",
    size: ["One Size"],
    brand: "Mango",
    material: "Leather",
    rating: 4.6,
    isNew: false,
    isFavorite: false,
  },
]

export const useStore = create<Store>((set, get) => ({
  favorites: products.filter((p) => p.isFavorite),
  cartItems: [
    { ...products[1], quantity: 1, selectedSize: "M" },
    { ...products[3], quantity: 2, selectedSize: "L" },
  ],

  toggleFavorite: (productId: number) => {
    const product = products.find((p) => p.id === productId)
    if (!product) return

    set((state) => {
      const isFavorited = state.favorites.some((f) => f.id === productId)
      if (isFavorited) {
        return { favorites: state.favorites.filter((f) => f.id !== productId) }
      } else {
        return { favorites: [...state.favorites, product] }
      }
    })
  },

  updateCartQuantity: (productId: number, change: number) => {
    set((state) => ({
      cartItems: state.cartItems
        .map((item) => (item.id === productId ? { ...item, quantity: Math.max(0, item.quantity + change) } : item))
        .filter((item) => item.quantity > 0),
    }))
  },

  removeFromCart: (productId: number) => {
    set((state) => ({
      cartItems: state.cartItems.filter((item) => item.id !== productId),
    }))
  },

  addToCart: (product: Product, selectedSize?: string) => {
    set((state) => {
      const existingItem = state.cartItems.find((item) => item.id === product.id)
      const size = selectedSize || product.size[0] || "M"

      if (existingItem) {
        return {
          cartItems: state.cartItems.map((item) =>
            item.id === product.id ? { ...item, quantity: item.quantity + 1 } : item,
          ),
        }
      } else {
        return {
          cartItems: [...state.cartItems, { ...product, quantity: 1, selectedSize: size }],
        }
      }
    })
  },
}))

export { products }
