"use client"

import { create } from "zustand"

export interface Product {
  id: number
  name: string
  price: number
  image: string
  category: string
  gender: string
  color: string
  size: string[]
  brand: string
  material: string
  rating: number
  isNew: boolean
  isFavorite: boolean
}

export interface CartItem extends Product {
  quantity: number
  selectedSize: string
}

interface Store {
  favorites: Product[]
  cartItems: CartItem[]
  toggleFavorite: (productId: number) => void
  updateCartQuantity: (productId: number, change: number) => void
  removeFromCart: (productId: number) => void
  addToCart: (product: Product, selectedSize?: string) => void
}

const products: Product[] = [
  // T-shirts - Men
  {
    id: 1,
    name: "Classic Cotton T-Shirt",
    price: 25,
    image: "/placeholder.svg?height=400&width=300&text=Classic+T-Shirt",
    category: "T-shirts",
    gender: "Men",
    color: "White",
    size: ["S", "M", "L", "XL"],
    brand: "H&M",
    material: "Cotton",
    rating: 4.5,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 2,
    name: "Premium Basic Tee",
    price: 35,
    image: "/placeholder.svg?height=400&width=300&text=Premium+Tee",
    category: "T-shirts",
    gender: "Men",
    color: "Black",
    size: ["M", "L", "XL", "XXL"],
    brand: "Zara",
    material: "Cotton",
    rating: 4.7,
    isNew: true,
    isFavorite: false,
  },
  {
    id: 3,
    name: "Vintage Style T-Shirt",
    price: 30,
    image: "/placeholder.svg?height=400&width=300&text=Vintage+Tee",
    category: "T-shirts",
    gender: "Men",
    color: "Gray",
    size: ["S", "M", "L"],
    brand: "Mango",
    material: "Cotton",
    rating: 4.3,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 4,
    name: "Graphic Print Tee",
    price: 28,
    image: "/placeholder.svg?height=400&width=300&text=Graphic+Tee",
    category: "T-shirts",
    gender: "Men",
    color: "Blue",
    size: ["M", "L", "XL"],
    brand: "Pull&Bear",
    material: "Cotton",
    rating: 4.2,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 5,
    name: "Organic Cotton T-Shirt",
    price: 40,
    image: "/placeholder.svg?height=400&width=300&text=Organic+Tee",
    category: "T-shirts",
    gender: "Men",
    color: "Green",
    size: ["S", "M", "L", "XL"],
    brand: "H&M",
    material: "Cotton",
    rating: 4.6,
    isNew: true,
    isFavorite: false,
  },

  // T-shirts - Women
  {
    id: 6,
    name: "Soft Cotton Tee",
    price: 22,
    image: "/placeholder.svg?height=400&width=300&text=Soft+Tee",
    category: "T-shirts",
    gender: "Women",
    color: "Pink",
    size: ["XS", "S", "M", "L"],
    brand: "Zara",
    material: "Cotton",
    rating: 4.4,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 7,
    name: "Fitted Basic T-Shirt",
    price: 26,
    image: "/placeholder.svg?height=400&width=300&text=Fitted+Tee",
    category: "T-shirts",
    gender: "Women",
    color: "White",
    size: ["XS", "S", "M"],
    brand: "Bershka",
    material: "Cotton",
    rating: 4.3,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 8,
    name: "Oversized Tee",
    price: 32,
    image: "/placeholder.svg?height=400&width=300&text=Oversized+Tee",
    category: "T-shirts",
    gender: "Women",
    color: "Beige",
    size: ["S", "M", "L", "XL"],
    brand: "Stradivarius",
    material: "Cotton",
    rating: 4.5,
    isNew: true,
    isFavorite: false,
  },
  {
    id: 9,
    name: "V-Neck T-Shirt",
    price: 24,
    image: "/placeholder.svg?height=400&width=300&text=V-Neck+Tee",
    category: "T-shirts",
    gender: "Women",
    color: "Black",
    size: ["XS", "S", "M", "L"],
    brand: "Mango",
    material: "Cotton",
    rating: 4.2,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 10,
    name: "Striped Cotton Tee",
    price: 29,
    image: "/placeholder.svg?height=400&width=300&text=Striped+Tee",
    category: "T-shirts",
    gender: "Women",
    color: "Blue",
    size: ["S", "M", "L"],
    brand: "H&M",
    material: "Cotton",
    rating: 4.4,
    isNew: false,
    isFavorite: false,
  },

  // Shirts - Men
  {
    id: 11,
    name: "Formal White Shirt",
    price: 65,
    image: "/placeholder.svg?height=400&width=300&text=Formal+Shirt",
    category: "Shirts",
    gender: "Men",
    color: "White",
    size: ["M", "L", "XL", "XXL"],
    brand: "Zara",
    material: "Cotton",
    rating: 4.6,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 12,
    name: "Casual Denim Shirt",
    price: 55,
    image: "/placeholder.svg?height=400&width=300&text=Denim+Shirt",
    category: "Shirts",
    gender: "Men",
    color: "Blue",
    size: ["S", "M", "L", "XL"],
    brand: "H&M",
    material: "Denim",
    rating: 4.3,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 13,
    name: "Linen Summer Shirt",
    price: 70,
    image: "/placeholder.svg?height=400&width=300&text=Linen+Shirt",
    category: "Shirts",
    gender: "Men",
    color: "Beige",
    size: ["M", "L", "XL"],
    brand: "Mango",
    material: "Linen",
    rating: 4.5,
    isNew: true,
    isFavorite: false,
  },
  {
    id: 14,
    name: "Checkered Flannel Shirt",
    price: 48,
    image: "/placeholder.svg?height=400&width=300&text=Flannel+Shirt",
    category: "Shirts",
    gender: "Men",
    color: "Red",
    size: ["S", "M", "L", "XL"],
    brand: "Pull&Bear",
    material: "Cotton",
    rating: 4.2,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 15,
    name: "Oxford Button-Down",
    price: 75,
    image: "/placeholder.svg?height=400&width=300&text=Oxford+Shirt",
    category: "Shirts",
    gender: "Men",
    color: "Gray",
    size: ["M", "L", "XL", "XXL"],
    brand: "Zara",
    material: "Cotton",
    rating: 4.7,
    isNew: false,
    isFavorite: false,
  },

  // Shirts - Women
  {
    id: 16,
    name: "Silk Blouse",
    price: 85,
    image: "/placeholder.svg?height=400&width=300&text=Silk+Blouse",
    category: "Shirts",
    gender: "Women",
    color: "White",
    size: ["XS", "S", "M", "L"],
    brand: "Zara",
    material: "Silk",
    rating: 4.8,
    isNew: true,
    isFavorite: false,
  },
  {
    id: 17,
    name: "Cotton Work Shirt",
    price: 52,
    image: "/placeholder.svg?height=400&width=300&text=Work+Shirt",
    category: "Shirts",
    gender: "Women",
    color: "Blue",
    size: ["S", "M", "L"],
    brand: "Mango",
    material: "Cotton",
    rating: 4.4,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 18,
    name: "Floral Print Blouse",
    price: 58,
    image: "/placeholder.svg?height=400&width=300&text=Floral+Blouse",
    category: "Shirts",
    gender: "Women",
    color: "Pink",
    size: ["XS", "S", "M", "L"],
    brand: "H&M",
    material: "Viscose",
    rating: 4.3,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 19,
    name: "Oversized Shirt",
    price: 62,
    image: "/placeholder.svg?height=400&width=300&text=Oversized+Shirt",
    category: "Shirts",
    gender: "Women",
    color: "Black",
    size: ["S", "M", "L", "XL"],
    brand: "Bershka",
    material: "Cotton",
    rating: 4.5,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 20,
    name: "Satin Dress Shirt",
    price: 78,
    image: "/placeholder.svg?height=400&width=300&text=Satin+Shirt",
    category: "Shirts",
    gender: "Women",
    color: "Beige",
    size: ["XS", "S", "M"],
    brand: "Stradivarius",
    material: "Satin",
    rating: 4.6,
    isNew: true,
    isFavorite: false,
  },

  // Dresses - Women
  {
    id: 21,
    name: "Summer Maxi Dress",
    price: 95,
    image: "/placeholder.svg?height=400&width=300&text=Maxi+Dress",
    category: "Dresses",
    gender: "Women",
    color: "Blue",
    size: ["XS", "S", "M", "L"],
    brand: "Zara",
    material: "Viscose",
    rating: 4.7,
    isNew: true,
    isFavorite: false,
  },
  {
    id: 22,
    name: "Little Black Dress",
    price: 120,
    image: "/placeholder.svg?height=400&width=300&text=Black+Dress",
    category: "Dresses",
    gender: "Women",
    color: "Black",
    size: ["XS", "S", "M", "L"],
    brand: "Mango",
    material: "Polyester",
    rating: 4.8,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 23,
    name: "Floral Midi Dress",
    price: 85,
    image: "/placeholder.svg?height=400&width=300&text=Midi+Dress",
    category: "Dresses",
    gender: "Women",
    color: "Pink",
    size: ["S", "M", "L"],
    brand: "H&M",
    material: "Cotton",
    rating: 4.5,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 24,
    name: "Casual Shirt Dress",
    price: 68,
    image: "/placeholder.svg?height=400&width=300&text=Shirt+Dress",
    category: "Dresses",
    gender: "Women",
    color: "White",
    size: ["XS", "S", "M", "L", "XL"],
    brand: "Bershka",
    material: "Cotton",
    rating: 4.3,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 25,
    name: "Evening Cocktail Dress",
    price: 150,
    image: "/placeholder.svg?height=400&width=300&text=Cocktail+Dress",
    category: "Dresses",
    gender: "Women",
    color: "Red",
    size: ["XS", "S", "M"],
    brand: "Zara",
    material: "Satin",
    rating: 4.9,
    isNew: true,
    isFavorite: false,
  },

  // Dresses - Kids
  {
    id: 26,
    name: "Kids Summer Dress",
    price: 35,
    image: "/placeholder.svg?height=400&width=300&text=Kids+Dress",
    category: "Dresses",
    gender: "Kids",
    color: "Pink",
    size: ["XS", "S", "M"],
    brand: "H&M",
    material: "Cotton",
    rating: 4.4,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 27,
    name: "Party Dress for Girls",
    price: 45,
    image: "/placeholder.svg?height=400&width=300&text=Party+Dress",
    category: "Dresses",
    gender: "Kids",
    color: "Blue",
    size: ["XS", "S"],
    brand: "Zara",
    material: "Polyester",
    rating: 4.6,
    isNew: true,
    isFavorite: false,
  },
  {
    id: 28,
    name: "Casual Kids Dress",
    price: 28,
    image: "/placeholder.svg?height=400&width=300&text=Casual+Dress",
    category: "Dresses",
    gender: "Kids",
    color: "White",
    size: ["XS", "S", "M"],
    brand: "Mango",
    material: "Cotton",
    rating: 4.2,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 29,
    name: "Floral Kids Dress",
    price: 32,
    image: "/placeholder.svg?height=400&width=300&text=Floral+Kids",
    category: "Dresses",
    gender: "Kids",
    color: "Green",
    size: ["XS", "S"],
    brand: "H&M",
    material: "Cotton",
    rating: 4.3,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 30,
    name: "Princess Style Dress",
    price: 55,
    image: "/placeholder.svg?height=400&width=300&text=Princess+Dress",
    category: "Dresses",
    gender: "Kids",
    color: "Pink",
    size: ["XS", "S", "M"],
    brand: "Zara",
    material: "Satin",
    rating: 4.7,
    isNew: true,
    isFavorite: false,
  },

  // Jeans - Men
  {
    id: 31,
    name: "Classic Straight Jeans",
    price: 75,
    image: "/placeholder.svg?height=400&width=300&text=Straight+Jeans",
    category: "Jeans",
    gender: "Men",
    color: "Blue",
    size: ["M", "L", "XL", "XXL"],
    brand: "Zara",
    material: "Denim",
    rating: 4.5,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 32,
    name: "Slim Fit Jeans",
    price: 68,
    image: "/placeholder.svg?height=400&width=300&text=Slim+Jeans",
    category: "Jeans",
    gender: "Men",
    color: "Black",
    size: ["S", "M", "L", "XL"],
    brand: "H&M",
    material: "Denim",
    rating: 4.4,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 33,
    name: "Relaxed Fit Jeans",
    price: 82,
    image: "/placeholder.svg?height=400&width=300&text=Relaxed+Jeans",
    category: "Jeans",
    gender: "Men",
    color: "Blue",
    size: ["M", "L", "XL", "XXL"],
    brand: "Mango",
    material: "Denim",
    rating: 4.3,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 34,
    name: "Distressed Jeans",
    price: 95,
    image: "/placeholder.svg?height=400&width=300&text=Distressed+Jeans",
    category: "Jeans",
    gender: "Men",
    color: "Blue",
    size: ["S", "M", "L", "XL"],
    brand: "Pull&Bear",
    material: "Denim",
    rating: 4.2,
    isNew: true,
    isFavorite: false,
  },
  {
    id: 35,
    name: "Dark Wash Jeans",
    price: 88,
    image: "/placeholder.svg?height=400&width=300&text=Dark+Jeans",
    category: "Jeans",
    gender: "Men",
    color: "Black",
    size: ["M", "L", "XL"],
    brand: "Zara",
    material: "Denim",
    rating: 4.6,
    isNew: false,
    isFavorite: false,
  },

  // Jeans - Women
  {
    id: 36,
    name: "High-Waisted Jeans",
    price: 72,
    image: "/placeholder.svg?height=400&width=300&text=High+Waist",
    category: "Jeans",
    gender: "Women",
    color: "Blue",
    size: ["XS", "S", "M", "L"],
    brand: "Zara",
    material: "Denim",
    rating: 4.7,
    isNew: true,
    isFavorite: false,
  },
  {
    id: 37,
    name: "Skinny Jeans",
    price: 65,
    image: "/placeholder.svg?height=400&width=300&text=Skinny+Jeans",
    category: "Jeans",
    gender: "Women",
    color: "Black",
    size: ["XS", "S", "M", "L"],
    brand: "H&M",
    material: "Denim",
    rating: 4.5,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 38,
    name: "Mom Jeans",
    price: 78,
    image: "/placeholder.svg?height=400&width=300&text=Mom+Jeans",
    category: "Jeans",
    gender: "Women",
    color: "Blue",
    size: ["S", "M", "L", "XL"],
    brand: "Bershka",
    material: "Denim",
    rating: 4.4,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 39,
    name: "Bootcut Jeans",
    price: 70,
    image: "/placeholder.svg?height=400&width=300&text=Bootcut+Jeans",
    category: "Jeans",
    gender: "Women",
    color: "Blue",
    size: ["XS", "S", "M", "L"],
    brand: "Mango",
    material: "Denim",
    rating: 4.3,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 40,
    name: "Ripped Jeans",
    price: 85,
    image: "/placeholder.svg?height=400&width=300&text=Ripped+Jeans",
    category: "Jeans",
    gender: "Women",
    color: "Blue",
    size: ["S", "M", "L"],
    brand: "Stradivarius",
    material: "Denim",
    rating: 4.2,
    isNew: true,
    isFavorite: false,
  },

  // Jackets - Men
  {
    id: 41,
    name: "Leather Jacket",
    price: 180,
    image: "/placeholder.svg?height=400&width=300&text=Leather+Jacket",
    category: "Jackets",
    gender: "Men",
    color: "Black",
    size: ["M", "L", "XL"],
    brand: "Zara",
    material: "Leather",
    rating: 4.8,
    isNew: true,
    isFavorite: false,
  },
  {
    id: 42,
    name: "Denim Jacket",
    price: 85,
    image: "/placeholder.svg?height=400&width=300&text=Denim+Jacket",
    category: "Jackets",
    gender: "Men",
    color: "Blue",
    size: ["S", "M", "L", "XL"],
    brand: "H&M",
    material: "Denim",
    rating: 4.4,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 43,
    name: "Bomber Jacket",
    price: 95,
    image: "/placeholder.svg?height=400&width=300&text=Bomber+Jacket",
    category: "Jackets",
    gender: "Men",
    color: "Green",
    size: ["M", "L", "XL"],
    brand: "Pull&Bear",
    material: "Polyester",
    rating: 4.3,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 44,
    name: "Blazer Jacket",
    price: 125,
    image: "/placeholder.svg?height=400&width=300&text=Blazer",
    category: "Jackets",
    gender: "Men",
    color: "Gray",
    size: ["M", "L", "XL", "XXL"],
    brand: "Mango",
    material: "Wool",
    rating: 4.6,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 45,
    name: "Windbreaker",
    price: 65,
    image: "/placeholder.svg?height=400&width=300&text=Windbreaker",
    category: "Jackets",
    gender: "Men",
    color: "Blue",
    size: ["S", "M", "L", "XL"],
    brand: "Nike",
    material: "Polyester",
    rating: 4.2,
    isNew: false,
    isFavorite: false,
  },

  // Jackets - Women
  {
    id: 46,
    name: "Cropped Leather Jacket",
    price: 165,
    image: "/placeholder.svg?height=400&width=300&text=Cropped+Leather",
    category: "Jackets",
    gender: "Women",
    color: "Black",
    size: ["XS", "S", "M", "L"],
    brand: "Zara",
    material: "Leather",
    rating: 4.7,
    isNew: true,
    isFavorite: false,
  },
  {
    id: 47,
    name: "Oversized Blazer",
    price: 98,
    image: "/placeholder.svg?height=400&width=300&text=Oversized+Blazer",
    category: "Jackets",
    gender: "Women",
    color: "Beige",
    size: ["S", "M", "L", "XL"],
    brand: "Mango",
    material: "Polyester",
    rating: 4.5,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 48,
    name: "Denim Jacket",
    price: 75,
    image: "/placeholder.svg?height=400&width=300&text=Women+Denim",
    category: "Jackets",
    gender: "Women",
    color: "Blue",
    size: ["XS", "S", "M", "L"],
    brand: "H&M",
    material: "Denim",
    rating: 4.3,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 49,
    name: "Puffer Jacket",
    price: 110,
    image: "/placeholder.svg?height=400&width=300&text=Puffer+Jacket",
    category: "Jackets",
    gender: "Women",
    color: "Pink",
    size: ["S", "M", "L"],
    brand: "Bershka",
    material: "Polyester",
    rating: 4.4,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 50,
    name: "Trench Coat",
    price: 145,
    image: "/placeholder.svg?height=400&width=300&text=Trench+Coat",
    category: "Jackets",
    gender: "Women",
    color: "Beige",
    size: ["XS", "S", "M", "L"],
    brand: "Zara",
    material: "Cotton",
    rating: 4.8,
    isNew: true,
    isFavorite: false,
  },

  // Sportswear - Unisex
  {
    id: 51,
    name: "Running Shorts",
    price: 35,
    image: "/placeholder.svg?height=400&width=300&text=Running+Shorts",
    category: "Sportswear",
    gender: "Unisex",
    color: "Black",
    size: ["S", "M", "L", "XL"],
    brand: "Nike",
    material: "Polyester",
    rating: 4.5,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 52,
    name: "Yoga Leggings",
    price: 45,
    image: "/placeholder.svg?height=400&width=300&text=Yoga+Leggings",
    category: "Sportswear",
    gender: "Unisex",
    color: "Gray",
    size: ["XS", "S", "M", "L"],
    brand: "Adidas",
    material: "Polyester",
    rating: 4.6,
    isNew: true,
    isFavorite: false,
  },
  {
    id: 53,
    name: "Sports Bra",
    price: 28,
    image: "/placeholder.svg?height=400&width=300&text=Sports+Bra",
    category: "Sportswear",
    gender: "Women",
    color: "Pink",
    size: ["XS", "S", "M", "L"],
    brand: "Nike",
    material: "Polyester",
    rating: 4.4,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 54,
    name: "Track Pants",
    price: 55,
    image: "/placeholder.svg?height=400&width=300&text=Track+Pants",
    category: "Sportswear",
    gender: "Unisex",
    color: "Blue",
    size: ["S", "M", "L", "XL"],
    brand: "Adidas",
    material: "Polyester",
    rating: 4.3,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 55,
    name: "Athletic Tank Top",
    price: 32,
    image: "/placeholder.svg?height=400&width=300&text=Tank+Top",
    category: "Sportswear",
    gender: "Unisex",
    color: "White",
    size: ["S", "M", "L", "XL"],
    brand: "Puma",
    material: "Polyester",
    rating: 4.2,
    isNew: false,
    isFavorite: false,
  },

  // Hoodies - Unisex
  {
    id: 56,
    name: "Classic Hoodie",
    price: 65,
    image: "/placeholder.svg?height=400&width=300&text=Classic+Hoodie",
    category: "Hoodies",
    gender: "Unisex",
    color: "Gray",
    size: ["S", "M", "L", "XL", "XXL"],
    brand: "H&M",
    material: "Cotton",
    rating: 4.5,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 57,
    name: "Oversized Hoodie",
    price: 75,
    image: "/placeholder.svg?height=400&width=300&text=Oversized+Hoodie",
    category: "Hoodies",
    gender: "Unisex",
    color: "Black",
    size: ["M", "L", "XL", "XXL"],
    brand: "Zara",
    material: "Cotton",
    rating: 4.6,
    isNew: true,
    isFavorite: false,
  },
  {
    id: 58,
    name: "Zip-Up Hoodie",
    price: 70,
    image: "/placeholder.svg?height=400&width=300&text=Zip+Hoodie",
    category: "Hoodies",
    gender: "Unisex",
    color: "Blue",
    size: ["S", "M", "L", "XL"],
    brand: "Nike",
    material: "Cotton",
    rating: 4.4,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 59,
    name: "Cropped Hoodie",
    price: 58,
    image: "/placeholder.svg?height=400&width=300&text=Cropped+Hoodie",
    category: "Hoodies",
    gender: "Women",
    color: "Pink",
    size: ["XS", "S", "M", "L"],
    brand: "Bershka",
    material: "Cotton",
    rating: 4.3,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 60,
    name: "Graphic Print Hoodie",
    price: 68,
    image: "/placeholder.svg?height=400&width=300&text=Graphic+Hoodie",
    category: "Hoodies",
    gender: "Unisex",
    color: "White",
    size: ["S", "M", "L", "XL"],
    brand: "Pull&Bear",
    material: "Cotton",
    rating: 4.2,
    isNew: false,
    isFavorite: false,
  },

  // Sweaters
  {
    id: 61,
    name: "Wool Sweater",
    price: 85,
    image: "/placeholder.svg?height=400&width=300&text=Wool+Sweater",
    category: "Sweaters",
    gender: "Men",
    color: "Brown",
    size: ["M", "L", "XL"],
    brand: "Zara",
    material: "Wool",
    rating: 4.7,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 62,
    name: "Cashmere Pullover",
    price: 120,
    image: "/placeholder.svg?height=400&width=300&text=Cashmere",
    category: "Sweaters",
    gender: "Women",
    color: "Beige",
    size: ["XS", "S", "M", "L"],
    brand: "Mango",
    material: "Wool",
    rating: 4.8,
    isNew: true,
    isFavorite: false,
  },
  {
    id: 63,
    name: "Cable Knit Sweater",
    price: 75,
    image: "/placeholder.svg?height=400&width=300&text=Cable+Knit",
    category: "Sweaters",
    gender: "Unisex",
    color: "Gray",
    size: ["S", "M", "L", "XL"],
    brand: "H&M",
    material: "Knit",
    rating: 4.5,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 64,
    name: "Turtleneck Sweater",
    price: 68,
    image: "/placeholder.svg?height=400&width=300&text=Turtleneck",
    category: "Sweaters",
    gender: "Women",
    color: "Black",
    size: ["XS", "S", "M", "L"],
    brand: "Zara",
    material: "Knit",
    rating: 4.4,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 65,
    name: "Cardigan",
    price: 78,
    image: "/placeholder.svg?height=400&width=300&text=Cardigan",
    category: "Sweaters",
    gender: "Women",
    color: "Pink",
    size: ["S", "M", "L"],
    brand: "Stradivarius",
    material: "Knit",
    rating: 4.3,
    isNew: false,
    isFavorite: false,
  },

  // Shorts
  {
    id: 66,
    name: "Denim Shorts",
    price: 45,
    image: "/placeholder.svg?height=400&width=300&text=Denim+Shorts",
    category: "Shorts",
    gender: "Women",
    color: "Blue",
    size: ["XS", "S", "M", "L"],
    brand: "H&M",
    material: "Denim",
    rating: 4.3,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 67,
    name: "Chino Shorts",
    price: 38,
    image: "/placeholder.svg?height=400&width=300&text=Chino+Shorts",
    category: "Shorts",
    gender: "Men",
    color: "Beige",
    size: ["S", "M", "L", "XL"],
    brand: "Zara",
    material: "Cotton",
    rating: 4.4,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 68,
    name: "High-Waisted Shorts",
    price: 42,
    image: "/placeholder.svg?height=400&width=300&text=High+Waist+Shorts",
    category: "Shorts",
    gender: "Women",
    color: "Black",
    size: ["XS", "S", "M", "L"],
    brand: "Bershka",
    material: "Cotton",
    rating: 4.2,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 69,
    name: "Cargo Shorts",
    price: 52,
    image: "/placeholder.svg?height=400&width=300&text=Cargo+Shorts",
    category: "Shorts",
    gender: "Men",
    color: "Green",
    size: ["M", "L", "XL"],
    brand: "Pull&Bear",
    material: "Cotton",
    rating: 4.1,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 70,
    name: "Linen Shorts",
    price: 48,
    image: "/placeholder.svg?height=400&width=300&text=Linen+Shorts",
    category: "Shorts",
    gender: "Unisex",
    color: "White",
    size: ["S", "M", "L", "XL"],
    brand: "Mango",
    material: "Linen",
    rating: 4.5,
    isNew: true,
    isFavorite: false,
  },

  // Skirts
  {
    id: 71,
    name: "Mini Skirt",
    price: 35,
    image: "/placeholder.svg?height=400&width=300&text=Mini+Skirt",
    category: "Skirts",
    gender: "Women",
    color: "Black",
    size: ["XS", "S", "M", "L"],
    brand: "Zara",
    material: "Polyester",
    rating: 4.3,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 72,
    name: "Pleated Skirt",
    price: 48,
    image: "/placeholder.svg?height=400&width=300&text=Pleated+Skirt",
    category: "Skirts",
    gender: "Women",
    color: "Blue",
    size: ["XS", "S", "M"],
    brand: "H&M",
    material: "Polyester",
    rating: 4.4,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 73,
    name: "A-Line Skirt",
    price: 42,
    image: "/placeholder.svg?height=400&width=300&text=A-Line+Skirt",
    category: "Skirts",
    gender: "Women",
    color: "Red",
    size: ["S", "M", "L"],
    brand: "Mango",
    material: "Cotton",
    rating: 4.2,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 74,
    name: "Pencil Skirt",
    price: 55,
    image: "/placeholder.svg?height=400&width=300&text=Pencil+Skirt",
    category: "Skirts",
    gender: "Women",
    color: "Gray",
    size: ["XS", "S", "M", "L"],
    brand: "Zara",
    material: "Polyester",
    rating: 4.5,
    isNew: true,
    isFavorite: false,
  },
  {
    id: 75,
    name: "Maxi Skirt",
    price: 65,
    image: "/placeholder.svg?height=400&width=300&text=Maxi+Skirt",
    category: "Skirts",
    gender: "Women",
    color: "Green",
    size: ["S", "M", "L", "XL"],
    brand: "Stradivarius",
    material: "Viscose",
    rating: 4.6,
    isNew: false,
    isFavorite: false,
  },

  // Accessories
  {
    id: 76,
    name: "Leather Belt",
    price: 25,
    image: "/placeholder.svg?height=400&width=300&text=Leather+Belt",
    category: "Accessories",
    gender: "Unisex",
    color: "Brown",
    size: ["One Size"],
    brand: "Zara",
    material: "Leather",
    rating: 4.4,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 77,
    name: "Baseball Cap",
    price: 18,
    image: "/placeholder.svg?height=400&width=300&text=Baseball+Cap",
    category: "Accessories",
    gender: "Unisex",
    color: "Black",
    size: ["One Size"],
    brand: "Nike",
    material: "Cotton",
    rating: 4.2,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 78,
    name: "Silk Scarf",
    price: 35,
    image: "/placeholder.svg?height=400&width=300&text=Silk+Scarf",
    category: "Accessories",
    gender: "Women",
    color: "Pink",
    size: ["One Size"],
    brand: "H&M",
    material: "Silk",
    rating: 4.5,
    isNew: true,
    isFavorite: false,
  },
  {
    id: 79,
    name: "Sunglasses",
    price: 45,
    image: "/placeholder.svg?height=400&width=300&text=Sunglasses",
    category: "Accessories",
    gender: "Unisex",
    color: "Black",
    size: ["One Size"],
    brand: "Zara",
    material: "Polyester",
    rating: 4.3,
    isNew: false,
    isFavorite: false,
  },
  {
    id: 80,
    name: "Crossbody Bag",
    price: 65,
    image: "/placeholder.svg?height=400&width=300&text=Crossbody+Bag",
    category: "Accessories",
    gender: "Women",
    color: "Beige",
    size: ["One Size"],
    brand: "Mango",
    material: "Leather",
    rating: 4.6,
    isNew: false,
    isFavorite: false,
  },
]

export const useStore = create<Store>((set, get) => ({
  favorites: products.filter((p) => p.isFavorite),
  cartItems: [
    { ...products[1], quantity: 1, selectedSize: "M" },
    { ...products[3], quantity: 2, selectedSize: "L" },
  ],

  toggleFavorite: (productId: number) => {
    const product = products.find((p) => p.id === productId)
    if (!product) return

    set((state) => {
      const isFavorited = state.favorites.some((f) => f.id === productId)
      if (isFavorited) {
        return { favorites: state.favorites.filter((f) => f.id !== productId) }
      } else {
        return { favorites: [...state.favorites, product] }
      }
    })
  },

  updateCartQuantity: (productId: number, change: number) => {
    set((state) => ({
      cartItems: state.cartItems
        .map((item) => (item.id === productId ? { ...item, quantity: Math.max(0, item.quantity + change) } : item))
        .filter((item) => item.quantity > 0),
    }))
  },

  removeFromCart: (productId: number) => {
    set((state) => ({
      cartItems: state.cartItems.filter((item) => item.id !== productId),
    }))
  },

  addToCart: (product: Product, selectedSize?: string) => {
    set((state) => {
      const existingItem = state.cartItems.find((item) => item.id === product.id)
      const size = selectedSize || product.size[0] || "M"

      if (existingItem) {
        return {
          cartItems: state.cartItems.map((item) =>
            item.id === product.id ? { ...item, quantity: item.quantity + 1 } : item,
          ),
        }
      } else {
        return {
          cartItems: [...state.cartItems, { ...product, quantity: 1, selectedSize: size }],
        }
      }
    })
  },
}))

export { products }
